"""adds professor to many to many

Revision ID: 05c988439d6b
Revises: 922a50ca6dd8
Create Date: 2023-10-20 05:59:57.457408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c988439d6b'
down_revision = '922a50ca6dd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_subject_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professor', sa.String(), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_students_pet_id_pets'), 'pets', ['pet_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_students_wand_id_wands'), 'wands', ['wand_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_students_wand_id_wands'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_students_pet_id_pets'), type_='foreignkey')

    with op.batch_alter_table('student_subject_association', schema=None) as batch_op:
        batch_op.drop_column('professor')

    # ### end Alembic commands ###
