"""edits grade

Revision ID: 0f038c693833
Revises: a3c4e4f483bb
Create Date: 2023-10-20 06:39:39.036889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f038c693833'
down_revision = 'a3c4e4f483bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_students_pet_id_pets'), 'pets', ['pet_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_students_wand_id_wands'), 'wands', ['wand_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_students_wand_id_wands'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_students_pet_id_pets'), type_='foreignkey')

    # ### end Alembic commands ###
