"""isolate house

Revision ID: 17ade37e65b4
Revises: 95b2ffb70028
Create Date: 2023-10-18 16:09:28.168337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17ade37e65b4'
down_revision = '95b2ffb70028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wands')
    op.drop_table('students')
    op.drop_table('student_subject_association')
    op.drop_table('pets')
    op.drop_table('years')
    op.drop_table('subjects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subject', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('years',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('type', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_subject_association',
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.Column('subject_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='fk_student_subject_association_student_id_students'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name='fk_student_subject_association_subject_id_subjects')
    )
    op.create_table('students',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('house_id', sa.INTEGER(), nullable=True),
    sa.Column('wand_id', sa.INTEGER(), nullable=True),
    sa.Column('pet_id', sa.INTEGER(), nullable=True),
    sa.Column('year_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], name='fk_students_house_id_houses'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name='fk_students_pet_id_pets'),
    sa.ForeignKeyConstraint(['wand_id'], ['wands.id'], name='fk_students_wand_id_wands'),
    sa.ForeignKeyConstraint(['year_id'], ['years.id'], name='fk_students_year_id_years'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wands',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('wood', sa.VARCHAR(), nullable=True),
    sa.Column('core', sa.VARCHAR(), nullable=True),
    sa.Column('length', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
