"""adds subject class

Revision ID: 6a27f182f717
Revises: f8992d102e1b
Create Date: 2023-10-16 08:37:41.239537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a27f182f717'
down_revision = 'f8992d102e1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_students_subject_id_subjects'), 'subjects', ['subject_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_students_subject_id_subjects'), type_='foreignkey')
        batch_op.drop_column('subject_id')

    op.drop_table('subjects')
    # ### end Alembic commands ###
