"""changes string

Revision ID: 7534c8711345
Revises: 0f038c693833
Create Date: 2023-10-20 08:02:48.212452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7534c8711345'
down_revision = '0f038c693833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_students_wand_id_wands'), 'wands', ['wand_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_students_pet_id_pets'), 'pets', ['pet_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_students_pet_id_pets'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_students_wand_id_wands'), type_='foreignkey')

    # ### end Alembic commands ###
