"""adds student table

Revision ID: 839b24e597a1
Revises: 8f2a34553e92
Create Date: 2023-10-19 06:42:47.373305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839b24e597a1'
down_revision = '8f2a34553e92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.Column('wand_id', sa.Integer(), nullable=True),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], name=op.f('fk_students_house_id_houses')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_students_pet_id_pets')),
    sa.ForeignKeyConstraint(['wand_id'], ['wands.id'], name=op.f('fk_students_wand_id_wands')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    # ### end Alembic commands ###
