"""adds subjects

Revision ID: 922a50ca6dd8
Revises: 839b24e597a1
Create Date: 2023-10-19 21:00:14.382599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922a50ca6dd8'
down_revision = '839b24e597a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_subject_association',
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_student_subject_association_student_id_students')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_student_subject_association_subject_id_subjects'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_subject_association')
    op.drop_table('subjects')
    # ### end Alembic commands ###
