"""adds wands

Revision ID: b4b1a69b7f9e
Revises: 17ade37e65b4
Create Date: 2023-10-19 05:26:47.304604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4b1a69b7f9e'
down_revision = '17ade37e65b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wood', sa.String(), nullable=True),
    sa.Column('core', sa.String(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wands')
    # ### end Alembic commands ###
