"""updates wand class

Revision ID: f8992d102e1b
Revises: 2e53ebfa8a48
Create Date: 2023-10-16 08:13:35.059338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8992d102e1b'
down_revision = '2e53ebfa8a48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wands', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wands', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
